In [20]:
import numpy as np
ROW_COUNT = 6
COLUMN_COUNT = 7

In [21]:
def create_board():
    board = np.zeros((ROW_COUNT,COLUMN_COUNT))
    return board
board = create_board()

In [22]:
def drop_piece(board, row, col, piece):
    board[row][col] = piece

def is_valid_location(board, col):
    return board[ROW_COUNT-1][col]==0

def get_next_open_row(board, col):
    for r in range(ROW_COUNT):
        if board[r][col] == 0:
            return r
def print_board(board):
    print(np.flip(board, 0))
    
def winning_move(board, piece):
    # checking all horizontal locations
    for c in range(COLUMN_COUNT-3):
        for r in range(ROW_COUNT):
            if board[r][c] == piece and board[r][c+1]==piece and and board[r][c+2]==piece and board[r][c+3]==piece:
                return True
    #chekcing for veritcal locaitons

In [ ]:
game_over = False
turn = 0
while not game_over:
    #ask for player 1 input
    if turn==0:
        col = int(input("Player 1 make your selection (0,6):"))
        if is_valid_location(board, col):
            row = get_next_open_row(board,col)
            drop_piece(board, row, col, 1)
    #Ask for player 2 input
    else: 
        col = int(input("Player 2 make your selection (0,6):"))
        if is_valid_location(board, col):
            row = get_next_open_row(board,col)
            drop_piece(board, row, col, 2)
    print_board(board)
    turn += 1
    turn = turn %2

Player 1 make your selection (0,6):1
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]]
Player 2 make your selection (0,6):2
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 2. 0. 0. 0. 0.]]
Player 1 make your selection (0,6):3
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 2. 1. 0. 0. 0.]]
Player 2 make your selection (0,6):3
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 2. 0. 0. 0.]
 [0. 1. 2. 1. 0. 0. 0.]]


In [10]:
print(board)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]
